#version: "2"

#services:
ps_db:
  container_name: ps_db
  image: postgres
  env_file: .env
  ports:
    - "5433:5432"

ps_app:
  container_name: ps_app
  build: .
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  env_file: .env
  volumes:
    - .:/PostClips/:rw
  ports:
    - "3000:3000"
  #depends_on:
  links:
    - ps_db
