#version: "2.1"

#services:
psdb:
  container_name: psdb
  image: mysql
  env_file: .env
  ports:
    - "5433:3306"

psapp:
  container_name: psapp
  # build: .
  image: trum/postclipsms_back
  command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:setup && bundle exec rails s -p 3000 -b '0.0.0.0'"
  env_file: .env
  # volumes:
  #   - .:/PostClips/:rw
  ports:
    - "3000:3000"
  links:
    - psdb
